In [1]:
import numpy as np

In [2]:
N = 10
a = np.arange(0, N)
b = a [::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
x = np.arange(0, N)[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [49]:
N = 8
k =np.diag(np.arange(0, N+1))
print ('Cумма значений по диагонали:', np.sum(k))

Cумма значений по диагонали: 36


In [5]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )                         

from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [6]:
np.allclose( np.dot(a, linalg.solve(a, b)), b ) #проверка

True

In [34]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [35]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
new = next_user_stats

In [48]:
new_list = []
for element in (users_stats):
    elementLength = np.linalg.norm(element)
    newLength = np.linalg.norm(new)
    cosine = np.dot(element, new)/(elementLength*newLength)
    new_list.append(cosine)
max_cos = max(new_list)
print ('Самый похожий пользователь - ID', new_list.index(max_cos))
    

Самый похожий пользователь - ID 7
